services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: transfer-app
        restart: unless-stopped
        working_dir: /var/www/html
        env_file:
            - .env
        volumes:
            - ./.env:/var/www/html/.env:ro
            - storage_public:/var/www/html/storage/app/public
        expose:
            - "9000"
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - transfer-network


    queue-worker:
       build:
          context: .
          dockerfile: Dockerfile
       container_name: transfer-queue-worker
       restart: unless-stopped
       working_dir: /var/www/html
       env_file:
         - .env
       environment:
          CONTAINER_ROLE: queue-worker
       depends_on:
          mysql:
              condition: service_healthy
          app:
              condition: service_started
       networks:
          - transfer-network
       volumes:
           - ./.env:/var/www/html/.env:ro
           - storage_public:/var/www/html/storage/app/public


    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: transfer-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - storage_public:/var/www/html/storage/app/public:ro
        depends_on:
            app:
                condition: service_started
        networks:
            - transfer-network

    mysql:
        image: mysql:8.4
        container_name: transfer-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: money-transfer-management
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        expose:
            - "3306"
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 20s
        networks:
            - transfer-network

volumes:
    mysql-data:
    storage_public:

networks:
    transfer-network:
        driver: bridge
